package com.springbootrest.controller;

import com.springbootrest.model.User;
import com.springbootrest.model.UserRequest;
import com.springbootrest.model.UserResponse;
import com.springbootrest.service.IUserService;
import com.springbootrest.util.JwtUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/user")
public class UserController {

    @Autowired
    private IUserService userService; //Has a relation

    @Autowired
    private JwtUtil jwtUtil;



    //1. Save User Data In Database
    @PostMapping("/save")
    public ResponseEntity<String> saveUser(@RequestBody User user){

        Integer id= userService.saveUser(user);
        String body= "User "+id+" Saved";
        //return new ResponseEntity<String>(body, HttpStatus.OK);
        return ResponseEntity.ok(body);


    }

    // 2. Validate User and Generate Token(login)
    @PostMapping("/login")
    public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request )
    {
        // TODO: Validate username/password with Database
        String token= jwtUtil.generateToken(request.getUsername());
        return ResponseEntity.ok(new UserResponse(token,"Success! Generated By AshishITech"));

        //O/P

        //"token":-> Header --> "eyJhbGciOiJIUzUxMiJ9.
        // :-> Payload --> eyJzdWIiOiJBU0hJU0giLCJpc3MiOiJBc2hpc2hJVGVjaCIsImlhdCI6MTY0MDQxNjk4NywiZXhwIjoxNjQwNDE2OTg3fQ
        // :-> Signature -->.tT6mOU2266EOSnoetaQ-KvtAu6rtgR_hQEgrtOpAKv4KOw0yAwiyRxj4krW08pUgjEZAk7D3fTZDI7Ceao_04A",
        //  "message": "Success! Generated By AshishITech"


    }






}
